package com.doova.ktab.features.imagegen.service.impl;

import com.doova.ktab.features.imagegen.config.ImageGenProperties;
import com.doova.ktab.features.imagegen.exception.ImageGenerationException;
import com.doova.ktab.features.imagegen.service.ImageModelClient;
import com.google.genai.Client;
import com.google.genai.errors.ApiException;
import com.google.genai.types.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Slf4j
@Component
@RequiredArgsConstructor
public class GeminiImageModelClient implements ImageModelClient {

    private static final List<String> HARM_CATEGORIES = List.of(
            "HARM_CATEGORY_HATE_SPEECH",
            "HARM_CATEGORY_DANGEROUS_CONTENT",
            "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            "HARM_CATEGORY_HARASSMENT"
    );

    private final Client vertexGenAiClient;
    private final ImageGenProperties properties;

    @Override
    public ImagePayload generateImage(String prompt, String aspectRatio) {
        String model = properties.getAiModel();
        log.info("Generating image via Gemini model: {}, aspectRatio: {}", model, aspectRatio);

        List<SafetySetting> safetySettings = new ArrayList<>();
        for (String category : HARM_CATEGORIES) {
            safetySettings.add(SafetySetting.builder()
                    .category(category)
                    .threshold("BLOCK_LOW_AND_ABOVE")
                    .build());
        }

        ImageConfig.Builder imageConfigBuilder = ImageConfig.builder();
        if (aspectRatio != null && !aspectRatio.isBlank()) {
            imageConfigBuilder.aspectRatio(aspectRatio);
        }
        if (properties.getImageSize() != null && !properties.getImageSize().isBlank()) {
            imageConfigBuilder.imageSize(properties.getImageSize());
        }

        GenerateContentConfig config = GenerateContentConfig.builder()
                .responseModalities(List.of("IMAGE"))
                .imageConfig(imageConfigBuilder.build())
                .safetySettings(safetySettings)
                .candidateCount(1)
                .build();

        Content content = Content.builder()
                .role("user")
                .parts(List.of(Part.fromText(prompt)))
                .build();

        GenerateContentResponse response;
        try {
            response = vertexGenAiClient.models.generateContent(model, List.of(content), config);
        } catch (ApiException e) {
            log.error("Gemini API error during image generation (HTTP {}): {}", e.code(), e.getMessage());
            boolean retryable = e.code() == 429 || e.code() >= 500;
            throw new ImageGenerationException("Gemini API error: HTTP " + e.code(), retryable, e);
        } catch (Exception e) {
            log.error("Unexpected error during image generation: {}", e.getMessage(), e);
            throw new ImageGenerationException("Image generation failed unexpectedly", true, e);
        }

        List<Part> parts = response.parts();
        if (parts != null) {
            for (Part part : parts) {
                if (part.inlineData().isPresent() && part.inlineData().get().data().isPresent()) {
                    byte[] bytes = part.inlineData().get().data().get();
                    String mime = part.inlineData().get().mimeType().orElse("image/png");
                    log.info("Extracted generated image bytes ({} bytes, mime: {})", bytes.length, mime);
                    return new ImagePayload(bytes, mime, model);
                }
            }
        }

        String finishReason = "unknown";
        try {
            if (response.candidates().isPresent() && !response.candidates().get().isEmpty()) {
                finishReason = response.candidates().get().get(0).finishReason().map(Object::toString).orElse("unknown");
            }
        } catch (Exception ignored) {
        }

        log.warn("Gemini returned no image parts. FinishReason: {}", finishReason);
        throw new ImageGenerationException("No image generated by Gemini (finishReason=" + finishReason + ")", true);
    }
}
