package com.doova.ktab.features.extraction.dto;

public enum WarningCode {
    TOC_PAGE_MISMATCH, MISSING_CHAPTERS, DUPLICATE_HEADING, INVALID_RANGE, TOC_PAGE_OUT_OF_RANGE, EMPTY_CHAPTER,
    SHORT_CHAPTER, LARGE_GAP, LOW_ARABIC_RATIO, EXTRACTION_ARTIFACTS, NO_STRUCTURE, IMAGE_ONLY_PAGES
}
