package com.doova.ktab.features.imagegen.service;

import com.doova.ktab.features.imagegen.dto.request.GenerateImageRequest;
import com.doova.ktab.features.imagegen.dto.response.GenerateImageResponse;
import com.doova.ktab.features.imagegen.dto.response.ImageStatusResponse;
import com.doova.ktab.model.user.User;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.UUID;

public interface ImageGenService {

    /**
     * Submits an asynchronous image generation request for a book.
     *
     * @param bookId  The target book identifier
     * @param request The user's creative context and filter parameters
     * @param user    The authenticated user
     * @return Status response indicating QUEUED state and tracking ID
     */
    ImageStatusResponse submitGeneration(Long bookId, GenerateImageRequest request, User user);

    /**
     * Retrieves the current processing status and resolved URL for a generated image.
     *
     * @param bookId  The target book identifier
     * @param imageId The unique image identifier
     * @param user    The authenticated user
     * @return Status response
     */
    ImageStatusResponse getStatus(Long bookId, UUID imageId, User user);

    /**
     * Retrieves the complete details of a specific generated image.
     *
     * @param bookId  The target book identifier
     * @param imageId The unique image identifier
     * @param user    The authenticated user
     * @return Complete image response
     */
    GenerateImageResponse getImage(Long bookId, UUID imageId, User user);

    /**
     * Retrieves paginated gallery of images generated by the user for a specific book.
     *
     * @param bookId   The target book identifier
     * @param user     The authenticated user
     * @param pageable Pagination and sorting criteria
     * @return Page of GeneratedImageResponse
     */
    Page<GenerateImageResponse> listImages(Long bookId, User user, Pageable pageable);

    /**
     * Deletes a generated image and purges its artifact from Cloudflare R2.
     *
     * @param bookId  The target book identifier
     * @param imageId The unique image identifier
     * @param user    The authenticated user
     */
    void deleteImage(Long bookId, UUID imageId, User user);

    /**
     * Retrieves all supported aesthetic themes and aspect ratio filters for UI rendering.
     *
     * @return Filter options metadata
     */
    com.doova.ktab.features.imagegen.dto.response.ImageGenFiltersResponse getAvailableFilters();

    /**
     * Retrieves all images generated by the reader across all books, with optional book filter.
     *
     * @param bookIdFilter Optional book identifier to filter by
     * @param user         The authenticated user
     * @param pageable     Pagination and sorting criteria
     * @return Paginated gallery with book ID and book title per image
     */
    Page<GenerateImageResponse> listAllReaderImages(Long bookIdFilter, User user, Pageable pageable);

    /**
     * Retrieves all reader images separated/grouped by their parent book.
     *
     * @param user The authenticated user
     * @return List of book groups with book ID, book title, and images
     */
    java.util.List<com.doova.ktab.features.imagegen.dto.response.BookImageGroupResponse> getGroupedReaderImages(User user);

    /**
     * Retrieves a summary list of all books for which the user has generated images, including image counts.
     *
     * @param user The authenticated user
     * @return List of book summaries
     */
    java.util.List<com.doova.ktab.features.imagegen.dto.response.ReaderBookImageSummary> getReaderBooksWithImages(User user);
}
