package com.doova.ktab.features.imagegen.controller;

import com.doova.ktab.annotation.ApiVersion;
import com.doova.ktab.annotation.CurrentUser;
import com.doova.ktab.dto.ApiResponse;
import com.doova.ktab.enums.message.ApiMessageKey;
import com.doova.ktab.features.imagegen.dto.response.BookImageGroupResponse;
import com.doova.ktab.features.imagegen.dto.response.GenerateImageResponse;
import com.doova.ktab.features.imagegen.dto.response.ReaderBookImageSummary;
import com.doova.ktab.features.imagegen.service.ImageGenService;
import com.doova.ktab.model.user.User;
import com.doova.ktab.utils.response.ResponseUtils;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@ApiVersion(1)
@RestController
@RequestMapping(path = "/reader/images", produces = "application/json")
@RequiredArgsConstructor
@Validated
@Tag(name = "Reader Image Gallery", description = "Endpoints for retrieving all AI-generated images across all books with book metadata and filtering")
public class ReaderImageGalleryController {

    private final ImageGenService imageGenService;
    private final MessageSource messageSource;

    @Operation(
            summary = "Get all reader-generated images (with optional book filter)",
            description = "Retrieves a paginated list of all images generated by the current reader across books, including bookId and bookTitle. Allows filtering by ?bookId=."
    )
    @GetMapping
    @PreAuthorize("hasAnyAuthority('READER')")
    public ResponseEntity<ApiResponse<Page<GenerateImageResponse>>> listAllReaderImages(
            @RequestParam(required = false) Long bookId,
            @CurrentUser User user,
            @PageableDefault(size = 12) Pageable pageable
    ) {
        Page<GenerateImageResponse> page = imageGenService.listAllReaderImages(bookId, user, pageable);
        return ResponseUtils.success(
                page,
                ApiMessageKey.IMAGE_GEN_LIST_FETCH_SUCCESS.getMessage(messageSource),
                HttpStatus.OK
        );
    }

    @Operation(
            summary = "Get all reader images grouped/separated by book",
            description = "Retrieves all reader images organized into groups separated by book, each group containing bookId, bookTitle, totalImages, and image list."
    )
    @GetMapping("/grouped")
    @PreAuthorize("hasAnyAuthority('READER')")
    public ResponseEntity<ApiResponse<List<BookImageGroupResponse>>> getGroupedReaderImages(
            @CurrentUser User user
    ) {
        List<BookImageGroupResponse> grouped = imageGenService.getGroupedReaderImages(user);
        return ResponseUtils.success(
                grouped,
                ApiMessageKey.IMAGE_GEN_LIST_FETCH_SUCCESS.getMessage(messageSource),
                HttpStatus.OK
        );
    }

    @Operation(
            summary = "Get list of books having generated images (for filter tabs)",
            description = "Returns a summary list of distinct books that the reader has generated illustrations for, including image counts."
    )
    @GetMapping("/books")
    @PreAuthorize("hasAnyAuthority('READER')")
    public ResponseEntity<ApiResponse<List<ReaderBookImageSummary>>> getReaderBooksWithImages(
            @CurrentUser User user
    ) {
        List<ReaderBookImageSummary> books = imageGenService.getReaderBooksWithImages(user);
        return ResponseUtils.success(
                books,
                ApiMessageKey.OPERATION_SUCCESS.getMessage(messageSource),
                HttpStatus.OK
        );
    }
}
